[package]
name = "screenpipe-app"
version = "0.1.87"
description = ""
authors = ["you"]
license = ""
repository = ""
default-run = "screenpipe-app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "=2.0.0-rc.9", features = [] }

[dependencies]
serde_json = "1.0"
tauri = { version = "2.0.0-rc.10", features = ["tray-icon", "devtools", "image-png", "image-ico"] }


# Logging
log = "0.4.17"

# Tokio
tokio = { version = "1.36.0", features = ["full"] }

# HTTP client
reqwest = { version = "0.12", features = ["json"] }

# Uuid
uuid = { version = "1.10.0", features = ["v4"] }

# Sentry 
sentry = { version = "0.34.0", features = ["tracing"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-appender = "0.2.3"
# broken not compatible w tauri2?
# sentry-tauri = "0.2"

# Autostart
tauri-plugin-autostart = "2.0.0-beta.9"

# Chrono
tauri-plugin-shell = "2.0.0-rc.2"
tauri-plugin-store = "2.0.0-beta"


anyhow = "1.0.71"

# System information
sysinfo = "0.29.0"

# hakc 
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs" }

# server
axum = "0.6"
serde = "1.0.160"


tauri-plugin-fs = "2.0.0-beta"
tauri-plugin-notification = "2.0.0-alpha.3"
tauri-plugin-updater = "2.0.0-alpha.2"
tauri-plugin-dialog = "2.0.0-alpha.2"
tauri-plugin-os = "2.0.0-alpha.2"
tauri-plugin-process = "2.0.0-alpha.2"


# M series MacOS
[target.'cfg(target_os = "macos")'.dependencies]
screenpipe-server = { path = "../../../../screenpipe-server", features = ["metal"] }
screenpipe-audio = { path = "../../../../screenpipe-audio", features = ["metal"] }

# Linux
[target.'cfg(target_os = "linux")'.dependencies]
screenpipe-server = { path = "../../../../screenpipe-server", features = [] }
screenpipe-audio = { path = "../../../../screenpipe-audio", features = [] }

# Windows
[target.'cfg(target_os = "windows")'.dependencies]
screenpipe-server = { path = "../../../../screenpipe-server", features = [] }
screenpipe-audio = { path = "../../../../screenpipe-audio", features = [] }

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-cli = "2.0.0-alpha.2"
# tauri-plugin-updater = "2.0.0-alpha.2"

[features]
cuda = ["screenpipe-server/cuda", "screenpipe-audio/cuda"]
metal = ["screenpipe-server/metal", "screenpipe-audio/metal"]

default = ["custom-protocol"]

# TODOS one day
coreml = []
openblas = []
opencl = []
rocm = []

# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
